keys:
  - &yubikey1 age1yubikey1qtkqf9lnj6clvyt4g7gyyavhyevdylk3pfqxckn7d5azdqj2hfyngkym037
  - &yubikey2 age1yubikey1qtvjaflu0lu329y43l562v2g2kcvgn3x0mpsuvc6v92xyf2c8yv327kdq00
  - &squirtle age1hjce6z08fe9f8tgn7cdh3ald0php42873rjhpfsu6gygg8n6hc8qnqn34f

creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - age:
          - *yubikey1
          - *yubikey2
          - *squirtle